# This is a basic workflow to help you get started with Actions
name: kapellmeister-agent CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run Buildx on develop
        if: github.ref_name == 'develop'
        run: |
          docker buildx build \
            --force-rm \
            --compress \
            --no-cache \
            --pull \
            --progress plain \
            --platform ${{ steps.buildx.outputs.platforms }} \
            --push \
            --tag belichberghub/kapellmeister-agent:develop \
            .

      - name: Run Buildx on main
        if: github.ref_name == 'main'
        run: |
          docker buildx build \
            --force-rm \
            --compress \
            --no-cache \
            --pull \
            --progress plain \
            --platform ${{ steps.buildx.outputs.platforms }} \
            --push \
            --tag belichberghub/kapellmeister-agent:latest \
            .
